### PR TITLE
chore(typescript): add types declaration file for typescript

### PR DESCRIPTION
**Pull request by valotvince**
Add types for project using typescript :) 

Feel free to suggest a better path for those types !

### CODE REVIEW

**Review by Slashgear — APPROVED** [review]

**Review by flepretre — APPROVED** [review]
Nice 👍 
We will need to port this in #97 

Can we test/validate that types matches the function definitions? If someone change the function signature without impacting the declaration file no body will notice :/

**Review by hpierre74 — APPROVED** [review]

**Comment by valotvince** [comment]
@flepretre Yep that is the downside of having a separate d.ts ... Maybe we could rewrite the lib in Typescript ? 😍

**Review by fdubost — APPROVED** [review]
I'm not an expert of types but LGTM

**Comment by flepretre** [comment]
> @flepretre Yep that is the downside of having a separate d.ts ... Maybe we could rewrite the lib in Typescript ? 😍

Of course if you have the time to do so. I prefer the project to be rewritten in TS than exposing some misleading types, but I won't do it myself 😅

**Pull request merged**
